name: Component Detection

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

permissions:
  contents: write
  id-token: write

jobs:
  dependency-submission:
    strategy:
      fail-fast: false
    runs-on: 'windows-latest'
    name: Component Detection
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          # dotnet-quality: 'preview'
          dotnet-version: '10.x'
       # Example AUTH - https://github.com/actions/setup-dotnet?tab=readme-ov-file#setting-up-authentication-for-nuget-feeds
        #   source-url: https://pkgs.dev.azure.com/<your-organization>/_packaging/<your-feed-name>/nuget/v3/index.json
        # env:
        #   NUGET_AUTH_TOKEN: ${{secrets.AZURE_DEVOPS_PAT}} # Note, create a secret with this name in Settings

      - name: Ensure .NET MAUI workload is installed
        shell: pwsh
        run: |
            dotnet workload restore
            
      # Component detection inspects resolved nuget packages: https://github.com/microsoft/component-detection/blob/main/docs/detectors/nuget.md
      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Component Detection
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.0
        with:
          filePath: '.'
